// src/components/SequencerPlaybackControls.vue
<template>
    <div id="sequencer-container-playback" class="flex flex-col items-center space-y-4">
        <div class="flex space-x-2">
            <AppSmallButton @click="playbackManager.playSequence()">
                Play
            </AppSmallButton>
            <AppSmallButton @click="playbackManager.pauseSequence()"
                :disabled="playbackManager.getStatus() === SequenceStatus.Paused">
                Pause
            </AppSmallButton>
            <AppSmallButton @click="playbackManager.stopSequence()">
                Stop
            </AppSmallButton>
            <AppSmallCheckbox v-model="loopEnabled">
                <template #rightLabel>Loop</template>
            </AppSmallCheckbox>
        </div>
    </div>
</template>

<script setup lang="ts">
import { ref, inject, watch } from 'vue';
import { sequencerPlaybackManagerKey } from '@/utils/injection-keys';
import { SequencerPlaybackManager } from '@/services/SequencerPlaybackManager';
import AppSmallButton from '@/components/AppSmallButton.vue';
import AppSmallCheckbox from '@/components/AppSmallCheckbox.vue';
import { SequenceStatus } from '@/utils/types';

const playbackManager = inject(sequencerPlaybackManagerKey) as SequencerPlaybackManager;

const loopEnabled = ref(playbackManager.loopEnabled);

watch(loopEnabled, (newValue) => {
    playbackManager.loopEnabled = newValue;
});
</script>

// src/features/sequencer/components/SequencerPlaybackControls.tsx
// src/features/components/SequencerPlaybackControls.tsx

import React, { useState, useEffect } from 'react';
import { SequenceStatus } from '@/core/enums/sequenceStatus';
import AppSmallButton from '@/common/components/AppSmallButton';
import AppSmallCheckbox from '@/common/components/AppSmallCheckbox';

// Mock playback manager
const playbackManager = {
  playSequence: () => console.log('Play sequence'),
  pauseSequence: () => console.log('Pause sequence'),
  stopSequence: () => console.log('Stop sequence'),
  getStatus: () => SequenceStatus.Playing,
  loopEnabled: false,
};

interface SequencerPlaybackControlsProps {
  className?: string;
}

const SequencerPlaybackControls: React.FC<SequencerPlaybackControlsProps> = ({ className }) => {
  const [loopEnabled, setLoopEnabled] = useState(playbackManager.loopEnabled);

  useEffect(() => {
    playbackManager.loopEnabled = loopEnabled;
  }, [loopEnabled]);

  return (
    <div id="sequencer-container-playback" className={`flex flex-col items-center space-y-4 ${className}`}>
      <div className="flex space-x-2">
        <AppSmallButton onClick={() => playbackManager.playSequence()}>
          Play
        </AppSmallButton>
        <AppSmallButton
          onClick={() => playbackManager.pauseSequence()}
          disabled={playbackManager.getStatus() === SequenceStatus.Paused}
        >
          Pause
        </AppSmallButton>
        <AppSmallButton onClick={() => playbackManager.stopSequence()}>
          Stop
        </AppSmallButton>
        <AppSmallCheckbox
          checked={loopEnabled}
          onChange={(e) => setLoopEnabled(e.target.checked)}
          rightLabel="Loop"
        />
      </div>
    </div>
  );
};

export default SequencerPlaybackControls;
