// src/common/components/AppSmallCheckbox.tsx
// src/common/components/AppSmallCheckbox.tsx

import React, { forwardRef } from 'react';

interface AppSmallCheckboxProps extends React.InputHTMLAttributes<HTMLInputElement> {
  leftLabel?: React.ReactNode;
  rightLabel?: React.ReactNode;
}

const AppSmallCheckbox = forwardRef<HTMLInputElement, AppSmallCheckboxProps>(
  ({ leftLabel, rightLabel, ...props }, ref) => {
    return (
      <div className="form-control">
        <label className="label cursor-pointer">
          {leftLabel && <span className="label-text">{leftLabel}</span>}
          <input
            ref={ref}
            type="checkbox"
            className="checkbox checkbox-sm"
            {...props}
          />
          {rightLabel && <span className="label-text ml-1">{rightLabel}</span>}
        </label>
      </div>
    );
  }
);

export default AppSmallCheckbox;

// src/components/AppSmallCheckbox.vue
<template>
    <div class="form-control">
        <label class="label cursor-pointer">
            <span class="label-text">
                <slot name="leftLabel"></slot>
            </span>
            <input v-model="model" type="checkbox" class="checkbox checkbox-sm" />
            <span class="label-text ml-1">
                <slot name="rightLabel"></slot>
            </span>
        </label>
    </div>
</template>
<script setup lang="ts">
const model = defineModel();
</script>
