// src/features/sequencer/components/SequencerTracks.tsx
// src/features/sequencer/SequencerTracks.tsx

import React, { useCallback, useMemo } from 'react';
import { StepPosition } from '@/core/interfaces/sequencer';

// Mock managers
const trackManager = {
  toggleTrackMuted: (id: number) => console.log(`Toggle mute for track ${id}`),
  toggleTrackSolo: (id: number) => console.log(`Toggle solo for track ${id}`),
  getTrackMuted: (id: number) => false,
  getTrackSolo: (id: number) => false,
  toggleStepActive: (trackId: number, stepIndex: number) => console.log(`Toggle step ${stepIndex} for track ${trackId}`),
  getStepActive: (trackId: number, stepIndex: number) => Math.random() > 0.5,
};

// Mock stores
const trackStore = {
  tracks: [
    { id: 0, steps: Array(16).fill(null) },
    { id: 1, steps: Array(16).fill(null) },
    { id: 2, steps: Array(16).fill(null) },
  ],
};

const playbackStore = {
  state: { visualStep: 0 },
};

const SequencerTracks: React.FC = () => {
  const isCurrentStep = useCallback((stepIndex: number) =>
    stepIndex === playbackStore.state.visualStep, []);

  const renderTrackControls = useCallback((track: { id: number }) => (
    <div className="flex items-center space-x-2 hover:opacity-100 opacity-70 transition ease-in-out duration-150">
      <button
        onClick={() => trackManager.toggleTrackMuted(track.id)}
        className={`w-8 h-8 rounded-full focus:outline-none transition-colors duration-150 ${trackManager.getTrackMuted(track.id) ? 'bg-red-500' : 'bg-gray-300'
          }`}
      >
        M
      </button>
      <button
        onClick={() => trackManager.toggleTrackSolo(track.id)}
        className={`w-8 h-8 rounded-full focus:outline-none transition-colors duration-150 ${trackManager.getTrackSolo(track.id) ? 'bg-green-500' : 'bg-gray-300'
          }`}
      >
        S
      </button>
    </div>
  ), []);

  const renderTrackSteps = useCallback((track: { id: number, steps: any[] }) => (
    <div className="track-steps flex-grow flex">
      {track.steps.map((_, stepIndex) => (
        <div
          key={stepIndex}
          onClick={() => trackManager.toggleStepActive(track.id, stepIndex)}
          className={`w-8 h-8 m-0.5 rounded-md cursor-pointer transition-all duration-150 ${trackManager.getStepActive(track.id, stepIndex) ? 'bg-ts-blue' : 'bg-gray-200'
            } ${isCurrentStep(stepIndex) ? 'ring-2 ring-yellow-400' : ''} ${trackManager.getTrackMuted(track.id) && !trackManager.getTrackSolo(track.id) ? 'opacity-50' : ''
            }`}
        />
      ))}
    </div>
  ), [isCurrentStep]);

  const trackElements = useMemo(() =>
    trackStore.tracks.map(track => (
      <div key={track.id} className="flex items-center space-x-2 hover:opacity-100">
        {renderTrackControls(track)}
        {renderTrackSteps(track)}
      </div>
    )), [renderTrackControls, renderTrackSteps]);

  return (
    <div id="sequencer-tracks-container" className="flex flex-col space-y-2">
      {trackElements}
    </div>
  );
};

export default SequencerTracks;

// src/components/SequencerTracks.vue
<template>
    <div id="sequencer-tracks-container" class="flex flex-col space-y-2">
        <div :id="`sequencer-track-${track.id}`" v-for="track in trackStore.tracks" :key="track.id"
            class="flex items-center space-x-2 hover:opacity-100">
            <div class="flex items-center space-x-2 hover:opacity-100 opacity-70 transition ease-in-out duration-150">
                <button @click="trackManager.toggleTrackMuted(track.id)"
                    :class="{ 'bg-red-500': trackManager.getTrackMuted(track.id), 'bg-gray-300': !trackManager.getTrackMuted(track.id) }"
                    class="w-8 h-8 rounded-full focus:outline-none transition-colors duration-150">
                    M
                </button>
                <button @click="trackManager.toggleTrackSolo(track.id)"
                    :class="{ 'bg-green-500': trackManager.getTrackSolo(track.id), 'bg-gray-300': !trackManager.getTrackSolo(track.id) }"
                    class="w-8 h-8 rounded-full focus:outline-none transition-colors duration-150">
                    S
                </button>
            </div>
            <div class="track-steps flex-grow flex">
                <div :id="`sequencer-track-${track.id}-step-${stepIndex}`" v-for="(_, stepIndex) in track.steps"
                    :key="stepIndex" @click="trackManager.toggleStepActive(track.id, stepIndex)"
                    class="w-8 h-8 m-0.5 rounded-md cursor-pointer transition-all duration-150" :class="{
                        'bg-ts-blue': trackManager.getStepActive(track.id, stepIndex),
                        'bg-gray-200': !trackManager.getStepActive(track.id, stepIndex),
                        'ring-2 ring-yellow-400': isCurrentStep(stepIndex),
                        'opacity-50': trackManager.getTrackMuted(track.id) && !trackManager.getTrackSolo(track.id),
                    }"
                    @contextmenu.prevent="handleContextMenu($event, { trackIndex: track.id, stepIndex: stepIndex })">
                </div>
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
import { computed, inject, markRaw } from 'vue';
import { useContextMenuStore } from '@/stores/contextMenuStore';
import { AppContextMenuItem } from '@/models/AppContextMenuItem';
import { AddTrackCommand, RemoveTrackCommand, OpenTrackSettings, OpenStepSettings } from '@/services/commands/SequencerCommands';
import { sequencerTrackManagerKey } from '@/utils/injection-keys';
import { SequencerTrackManager } from '@/services/SequencerTrackManager';
import { StepPosition, WindowDualPaneContent } from '@/utils/interfaces';
import SequencerTrackSettingsInstrumentsPane from './SequencerTrackSettingsInstrumentsPane.vue';
import SequencerTrackSettingsEffectsPane from './SequencerTrackSettingsEffectsPane.vue';
import { useStructureStore } from '@/stores/structureStore';
import { useTrackStore } from '@/stores/trackStore';
import { usePlaybackStore } from '@/stores/playbackStore';

const menuStore = useContextMenuStore();
const playbackStore = usePlaybackStore();
const structureStore = useStructureStore();
const trackStore = useTrackStore();

const trackManager = inject(sequencerTrackManagerKey) as SequencerTrackManager;

const isCurrentStep = computed(() => (stepIndex: number) => stepIndex === playbackStore.state.visualStep);

function createContextMenuItems(position: StepPosition) {
    if (structureStore.isTrackSelectionValid()) {
        const contents: WindowDualPaneContent[] = [
            { label: 'Instrument', component: markRaw(SequencerTrackSettingsInstrumentsPane) },
            { label: 'Effects', component: markRaw(SequencerTrackSettingsEffectsPane) },
        ]
        const contextMenuItems = [
            new AppContextMenuItem('Add track', new AddTrackCommand(position.trackIndex + 1)),
            new AppContextMenuItem('Remove track', new RemoveTrackCommand(position.trackIndex)),
            new AppContextMenuItem('Track settings', new OpenTrackSettings(contents, position.trackIndex)),
        ];
        if (structureStore.isStepSelectionValid()) {
            contextMenuItems.push(new AppContextMenuItem('Step settings', new OpenStepSettings(position)));
        }

        return contextMenuItems;
    }
}

// Handles right-click context menu for track operations
function handleContextMenu(event: MouseEvent, position: StepPosition) {
    structureStore.rightClickSelect(position);

    const items = createContextMenuItems(position);
    if (items) {
        menuStore.clearContextualItems(); // Clear previous contextual items
        menuStore.addContextualItems(items); // Add new contextual items
        menuStore.openContextMenu(event.clientX, event.clientY);
    }
}
</script>
