// src/components/AppRangeBar.vue
<template>
    <div id="app-range-bar-container" class="flex">
        <input v-model="model" type="range" class="range [--range-shdw:#5bcefa]" :step="props.step" :min="props.min"
            :max="props.max">
    </div>
</template>
<script setup lang="ts">
interface Props {
    min?: number;
    max?: number;
    step?: number;
}
const props = withDefaults(defineProps<Props>(), {
    min: () => 0,
    max: () => 100,
    step: () => 1,
});

const model = defineModel();
</script>

// src/common/components/AppRangeBar.tsx
// src/features/component/AppRangeBar.tsx

import React, { forwardRef, ChangeEvent } from 'react';

interface AppRangeBarProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'onChange'> {
  min?: number;
  max?: number;
  step?: number;
  onChange?: (value: number) => void;
}

const AppRangeBar = forwardRef<HTMLInputElement, AppRangeBarProps>(
  ({ min = 0, max = 100, step = 1, onChange, ...props }, ref) => {
    const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
      const value = Number(event.target.value);
      if (onChange) {
        onChange(value);
      }
    };

    return (
      <div id="app-range-bar-container" className="flex">
        <input
          ref={ref}
          type="range"
          className="range [--range-shdw:#5bcefa]"
          min={min}
          max={max}
          step={step}
          onChange={handleChange}
          {...props}
        />
      </div>
    );
  }
);

export default AppRangeBar;
